spring.application.name=Rentora
spring.datasource.url=jdbc:mysql://localhost:3306/rentals_db
spring.datasource.username=root
spring.datasource.password=Amityadav@3750

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

cloudinary.cloud_name=de4txkajc
cloudinary.api_key=612497913211547
cloudinary.api_secret=fqrDdJ7tMI8uu1_UUXUkWBL7yMA